### ISSUE TITLE
Translate after - before label

### ISSUE THREAD

**Issue by prankyboy** [zurb/twentytwenty#49]
Yu - huuu
on which file I can translate after - before?
thx

**Comment by mhayes** [comment]
Right now it's using a CSS `:before` pseudo selector to set the text. If you wanted to change the text you will need to use CSS like so:

```css
.twentytwenty-after-label:before {
  content: "NEW AFTER TEXT";
}
.twentytwenty-before-label:before {
  content: "NEW BEFORE TEXT";
}
```
